/// <reference types="@cloudflare/workers-types" />

/**
 * Pure SQL builders for the station-scoped voice_tracks endpoints.
 *
 * Voice tracks are short audio assets (DJ "tracking" between songs) recorded
 * by humans or generated by AI. The audio bytes live in R2 under the key
 * returned by `generateStorageKey`; metadata + optional transcript persist in
 * D1's `voice_tracks` table (created by migration 0004).
 *
 * Mirrors the conventions of play-log-queries.ts and schedule-queries.ts:
 * - station-scoped: every builder takes a stationId and uses it as the first
 *   WHERE predicate, so cross-station leakage is impossible at the call site.
 * - parametric only — user data never interpolated into SQL strings.
 * - framework-free so it can be unit-tested without spinning up D1.
 *
 * The `voice_tracks.status` column has a CHECK constraint defined in migration
 * 0004 limiting values to ('draft','ready','aired','archived'). `VT_STATUSES`
 * mirrors that constraint so the API layer can validate before reaching D1.
 */

export const DEFAULT_LIMIT = 50;
export const MAX_LIMIT = 200;

export const VT_STATUSES = ['draft', 'ready', 'aired', 'archived'] as const;
export type VtStatus = (typeof VT_STATUSES)[number];

export function isAllowedStatus(value: unknown): value is VtStatus {
  return typeof value === 'string' && (VT_STATUSES as readonly string[]).includes(value);
}

export interface VoiceTrackRow {
  id: string;
  stationId: string;
  recordedBy: string | null;
  storageKey: string;
  durationMs: number;
  transcript: string | null;
  targetClockSlotId: string | null;
  status: VtStatus;
  aiGenerated: 0 | 1 | null;
  createdAt: string;
}

export interface VoiceTrackKeysetCursor {
  lastCreatedAt: string;
  lastId: string;
}

export interface ListVoiceTracksParams {
  stationId: string;
  status?: VtStatus;
  targetClockSlotId?: string;
  cursor?: VoiceTrackKeysetCursor;
  limit: number;
}

export interface VoiceTrackPatch {
  transcript?: string | null;
  targetClockSlotId?: string | null;
  status?: VtStatus;
  aiGenerated?: 0 | 1 | null;
}

export interface BuiltQuery {
  sql: string;
  params: unknown[];
}

export function clampLimit(value: number | undefined, max: number, def: number): number {
  if (value === undefined || !Number.isFinite(value) || value <= 0) return def;
  if (value > max) return max;
  return Math.floor(value);
}

function toBase64Url(input: string): string {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(input, 'utf8').toString('base64url');
  }
  const b64 = btoa(input);
  return b64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}

function fromBase64Url(input: string): string {
  if (typeof Buffer !== 'undefined') {
    return Buffer.from(input, 'base64url').toString('utf8');
  }
  let b64 = input.replace(/-/g, '+').replace(/_/g, '/');
  while (b64.length % 4 !== 0) b64 += '=';
  return atob(b64);
}

export function encodeCursor(cursor: VoiceTrackKeysetCursor): string {
  return toBase64Url(JSON.stringify(cursor));
}

export function decodeCursor(input: string | undefined | null): VoiceTrackKeysetCursor | null {
  if (!input) return null;
  try {
    const json = fromBase64Url(input);
    const parsed = JSON.parse(json) as unknown;
    if (
      typeof parsed === 'object' &&
      parsed !== null &&
      typeof (parsed as { lastCreatedAt?: unknown }).lastCreatedAt === 'string' &&
      typeof (parsed as { lastId?: unknown }).lastId === 'string'
    ) {
      return parsed as VoiceTrackKeysetCursor;
    }
    return null;
  } catch {
    return null;
  }
}

function requireStationId(stationId: string): void {
  if (!stationId) throw new Error('stationId is required');
}

/**
 * R2 key generator for voice track audio. Keys live under a per-station
 * prefix so a single `r2 object delete` glob can sweep a station's audio on
 * tenant offboarding.
 */
export function generateStorageKey(
  stationId: string,
  trackId: string,
  extension = 'mp3',
): string {
  requireStationId(stationId);
  if (!trackId) throw new Error('trackId is required');
  // Strip any leading dots from the extension; default to `mp3` if blank.
  const ext = (extension || 'mp3').replace(/^\.+/, '') || 'mp3';
  return `stations/${stationId}/voice-tracks/${trackId}.${ext}`;
}

const VT_COLUMNS =
  'id, station_id, recorded_by, storage_key, duration_ms, transcript, target_clock_slot_id, status, ai_generated, created_at';

export function buildVoiceTracksListQuery(p: ListVoiceTracksParams): BuiltQuery {
  requireStationId(p.stationId);
  const limit = clampLimit(p.limit, MAX_LIMIT, DEFAULT_LIMIT);

  const where: string[] = ['station_id = ?'];
  const params: unknown[] = [p.stationId];

  if (p.status) {
    if (!isAllowedStatus(p.status)) {
      throw new Error(`status must be one of ${VT_STATUSES.join(', ')}`);
    }
    where.push('status = ?');
    params.push(p.status);
  }
  if (p.targetClockSlotId) {
    where.push('target_clock_slot_id = ?');
    params.push(p.targetClockSlotId);
  }
  if (p.cursor) {
    where.push('(created_at, id) < (?, ?)');
    params.push(p.cursor.lastCreatedAt, p.cursor.lastId);
  }

  const sql = `SELECT ${VT_COLUMNS}
    FROM voice_tracks
    WHERE ${where.join(' AND ')}
    ORDER BY created_at DESC, id DESC
    LIMIT ${limit}`;

  return { sql, params };
}

export function buildVoiceTrackByIdQuery(stationId: string, id: string): BuiltQuery {
  requireStationId(stationId);
  if (!id) throw new Error('id is required');
  const sql = `SELECT ${VT_COLUMNS}
    FROM voice_tracks
    WHERE station_id = ? AND id = ?
    LIMIT 1`;
  return { sql, params: [stationId, id] };
}

export function buildVoiceTrackInsert(row: Omit<VoiceTrackRow, 'createdAt'>): BuiltQuery {
  if (!row.id) throw new Error('id is required');
  requireStationId(row.stationId);
  if (!row.storageKey) throw new Error('storageKey is required');
  if (
    typeof row.durationMs !== 'number' ||
    !Number.isFinite(row.durationMs) ||
    row.durationMs < 0
  ) {
    throw new Error('durationMs must be a non-negative number');
  }

  // Status defaults to 'draft' when caller passes a falsy value (matches
  // migration 0004 default).
  const status = (row.status ?? 'draft') as VtStatus;
  if (!isAllowedStatus(status)) {
    throw new Error(`status must be one of ${VT_STATUSES.join(', ')}`);
  }

  const sql = `INSERT INTO voice_tracks
    (id, station_id, recorded_by, storage_key, duration_ms, transcript, target_clock_slot_id, status, ai_generated, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'))`;

  const params: unknown[] = [
    row.id,
    row.stationId,
    row.recordedBy ?? null,
    row.storageKey,
    Math.floor(row.durationMs),
    row.transcript ?? null,
    row.targetClockSlotId ?? null,
    status,
    row.aiGenerated ?? 0,
  ];

  return { sql, params };
}

export function buildVoiceTrackUpdate(
  stationId: string,
  id: string,
  patch: VoiceTrackPatch,
): BuiltQuery {
  requireStationId(stationId);
  if (!id) throw new Error('id is required');

  const sets: string[] = [];
  const params: unknown[] = [];

  if (patch.transcript !== undefined) {
    sets.push('transcript = ?');
    params.push(patch.transcript);
  }
  if (patch.targetClockSlotId !== undefined) {
    sets.push('target_clock_slot_id = ?');
    params.push(patch.targetClockSlotId);
  }
  if (patch.status !== undefined) {
    if (!isAllowedStatus(patch.status)) {
      throw new Error(`status must be one of ${VT_STATUSES.join(', ')}`);
    }
    sets.push('status = ?');
    params.push(patch.status);
  }
  if (patch.aiGenerated !== undefined) {
    sets.push('ai_generated = ?');
    params.push(patch.aiGenerated);
  }

  if (sets.length === 0) throw new Error('no fields to update');

  // Station + id binds go last to match `WHERE station_id = ? AND id = ?`.
  params.push(stationId, id);

  const sql = `UPDATE voice_tracks
    SET ${sets.join(', ')}
    WHERE station_id = ? AND id = ?`;

  return { sql, params };
}

export function buildVoiceTrackDelete(stationId: string, id: string): BuiltQuery {
  requireStationId(stationId);
  if (!id) throw new Error('id is required');
  const sql = `DELETE FROM voice_tracks WHERE station_id = ? AND id = ?`;
  return { sql, params: [stationId, id] };
}
